name: flexyatra
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.0.0
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  equatable: ^2.0.0
  flutter_svg_provider: ^1.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
    - family: Koulen
      fonts: 
        - asset: assets/fonts/KoulenRegular.ttf
          weight: 400
    - family: Lexend Tera
      fonts: 
        - asset: assets/fonts/LexendTeraRegular.ttf
          weight: 400
    - family: Ligconsolata
      fonts: 
        - asset: assets/fonts/LigconsolataRegular.ttf
          weight: 400
    - family: Mali
      fonts: 
        - asset: assets/fonts/MaliExtraLight.ttf
          weight: 300
        - asset: assets/fonts/MaliBold.ttf
          weight: 700
        - asset: assets/fonts/MaliRegular.ttf
          weight: 400
        - asset: assets/fonts/MaliSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MaliLight.ttf
          weight: 300
    - family: Lexend Peta
      fonts: 
        - asset: assets/fonts/LexendPetaExtraLight.ttf
          weight: 200
